---
- name: Setup redmine servers
  hosts: all
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - docker-server

- name: Setup datadog
  hosts: webservers
  roles:
    - { role: datadog.datadog, become: yes }
    - datadog
...