---
- name: Setup redmine servers
  hosts: all

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - docker-server
    - { role: datadog.datadog, become: yes }
    - datadog
...