---
roles:
  - name: geerlingguy.pip
    version: 2.1.0
    source: https://galaxy.ansible.com
  - name: geerlingguy.docker
    version: 3.1.2
    source: https://galaxy.ansible.com
  - name: datadog.datadog
    version: 4.10.0
    source: https://galaxy.ansible.com

collections:
  - name: community.docker
    version: 1.7.0